INSERT INTO CURRENCIES (NUMERIC_CODE, ALPHABETIC_CODE)
VALUES (978, 'EUR');
INSERT INTO FX_RATES (ID, EFFECTIVE_DATE, EXCHANGE_RATE, SOURCE_CURRENCY, TARGET_CURRENCY)
VALUES (1, TODAY(), 1, 978, 978)